Remove hard failure if expiry extraction fails
EXPIRY is declared seperately to avoid masking return value

diff --git a/bin/letsencrypt_hooks b/bin/letsencrypt_hooks
--- a/bin/letsencrypt_hooks
+++ b/bin/letsencrypt_hooks
@@ -33,10 +33,9 @@ clean_challenge() {
 
 deploy_cert() {
   local DOMAIN="${1}" KEYFILE="${2}" CERTFILE="${3}" FULLCHAINFILE="${4}" CHAINFILE="${5}" TIMESTAMP="${6}"
-  local EXPIRY=$(date --date="$(openssl x509 -enddate -noout -in "$CERTFILE"|cut -d= -f 2)" +%s)
-  if [ $? -ne 0   ]; then
-    echo "failed to get the expiry date."
-    exit 1
+  local EXPIRY
+  if ! EXPIRY=$(date --date="$(openssl x509 -enddate -noout -in "$CERTFILE"|cut -d= -f 2)" +%s); then
+    echo "failed to get the expiry date"
   fi
 
   curl --silent --show-error --fail -XPOST \
