Fix sockproc possibly inheriting nginx's sockets/file descriptors.
When we launch the sockproc process from inside nginx, we explicitly try
to clear all extra file descriptors, so nginx doesn't inherit the nginx
processes sockets. If sockproc does inherit these sockets, then if nginx
gets stopped or restarted, sockproc takes over listening on those
sockets, which means nginx can't be started again.

However, the existing implementation of clearing these file descriptors
could fail under certain circumstances, leading to nginx being unable to
restart. It depends on how nginx is started, but this could reliably
fail under this scenario:

- nginx was started under an init script.
- nginx had worker processes running as a less privileged user.
- The user that originally ran the init start command was "cd"ed into a
  directory that the less privileged nginx worker user didn't have
  permissions to be in.

This was failing due to the `find` command being combined with `-exec
basename` to find the file descriptors to clear. `basename` would fail
if the current user didn't have permissions to be in the current
directory (even if it was only finding the basename of paths in /proc
which it did have permissions to). This led to no file descriptors being
cleared. The `find` command would also generate a warning message after
finishing about not being able to restore the initial directory.

To fix this:

- Our script to start sockproc now explicitly sets the current directory
  to `/`, so any commands that require permissions to be in the current
  directory should work.
- Extract the basename of the /proc/ paths using bash, instead of
  shelling out to the `basename` command.
- If for any reason, clearing the file descriptors based on /proc/ paths
  fails, also fallback to the more naive OS x approach in Linux too.

A test has been added to the test suite to test this behavior. Since the
Makefile was getting a little unwieldy (particularly with another test
that needed all the "worker perms" environment variables), shift the
commands used to run the tests into a wrapper shell script to make
things a bit easier to manage.

diff --git a/bin/start_sockproc b/bin/start_sockproc
--- a/bin/start_sockproc
+++ b/bin/start_sockproc
@@ -1,7 +1,16 @@
 #!/usr/bin/env bash
 
+set -u
+
 sock_file=/tmp/shell.sock
 pid_file=/tmp/auto-ssl-sockproc.pid
+
+# This script inherits the current directory from wherever nginx is launched,
+# which may be a private directory. To prevent the "find" command below from
+# generating "failed to restore initial working directory: Permission denied"
+# errors, change to the root directory where the nginx user will have
+# permissions.
+cd / || (echo "WARNING: start_sockproc could not set current directory to /" 1>&2)
 
 # We want to launch sockproc from inside nginx using os.execute (mainly just to
 # simplify the deployment of auto-ssl, so you don't have to worry about running
@@ -16,18 +25,23 @@ pid_file=/tmp/auto-ssl-sockproc.pid
 # See:
 # http://stackoverflow.com/a/4839945/222487
 # http://stackoverflow.com/a/23104923/222487
+file_descriptors_cleared="false"
 if [ -d /proc ]; then
   current_pid=$BASHPID
-  file_descriptors=$(find /proc/$current_pid/fd -type l -exec basename {} ';')
-  for fd in $file_descriptors; do
+  file_descriptors=$(find /proc/"$current_pid"/fd -type l)
+  for fd_path in $file_descriptors; do
+    # Extract just the fd number from the end of the path.
+    fd=${fd_path##*/}
     if ((fd > 2)); then
-      eval "exec $fd>&-"
+      eval "exec $fd>&-" && file_descriptors_cleared="true"
     fi
   done
+fi
 
-# If /proc isn't supported (eg, OS X), fallback to a simpler, naive mechanism
-# to wipe file descriptors > 2.
-else
+# If /proc isn't supported (eg, OS X), or an error occurred during the
+# proc-based "find", then fallback to a simpler, naive mechanism to wipe file
+# descriptors > 2.
+if [ "$file_descriptors_cleared" != "true" ]; then
   END=255
   for ((fd=3; fd <= END; fd++)); do
     eval "exec $fd>&-"
